import path from 'path';

export default async function (options: ChoreOptions) {
  const {projectDir, features} = options;
  const appName = path.basename(projectDir);

  const pkgJson = {
    name: appName,
    version: '0.1.0',
    description: `${appName} is generated by chore-cli.`,
    main: 'dist/index.js',
    module: `dist/${appName}.esm.js`,
    typings: 'dist/index.d.ts',
    scripts: {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    repository: {
      'type': 'git',
      'url': 'git+https://github.com/iwfan/chore-cli.git'
    },
    keywords: [
      'chore',
      'chore-cli'
    ],
    author: {
      'name': '',
      'email': ''
    },
    license: 'MIT',
    bugs: {
      'url': 'https://github.com/iwfan/chore-cli/issues'
    },
    homepage: 'https://github.com/iwfan/chore-cli#readme',
    files: [
      'dist'
    ],
  };

  if (features.includes('jest')) {
    pkgJson.scripts.test = 'jest';
  }

  Object.assign<FileContent, FileContent>(options.files, {
    'package.json': JSON.stringify(pkgJson, null, 2)
  });
}
