{
  "name": "<%= packageName %>",
  "version": "0.0.1",
  "description": "<%= packageName %> is generated by chore-cli.",
  "main": "dist/index.js",
  "module": "dist/<%= packageName %>.esm.js",
  "typings": "dist/index.d.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+<%= repoUrl %>.git"
  },
  "keywords": [
    "cli",
    "chore"
  ],
  "author": "<%- author %>",
  "license": "<%= license %>",
  "homepage": "<%= repoUrl %>#readme",
  "bugs": {
    "url": "<%= repoUrl %>/issues"
  }
}
